import Head from "next/head";
import { Rubik } from "@next/font/google";

export default function Home() {
  return (
    <>
      <Head>
        <title>Townsquare</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-y-scroll scroll-smooth">
        <section className="px-[5%] bg-black h-screen w-screen">
          <h2 className="font-aveFedan text-titleColor text-titleSize py-[5%]">
            townsquare
          </h2>
          <div className="flex flex-row-reverse items-center gap-[5%]">
            <div className="w-1/2">
              <img
                src="hero.png"
                alt="Hero text"
                className="object-contain h-full"
              />
            </div>
            <div className="w-1/2">
              <h3 className="text-white text-[3vw] font-bold leading-tight">
                The better way to find friends in your city.
              </h3>
              <p className="text-blue text-[1.5vw] leading-tight pt-[5%]">
                Visit the{" "}
                <span className="font-bold text-purple">townsquare </span>to
                find and connect with like-minded people around you.
              </p>
            </div>
          </div>
        </section>
        <section className="px-[5%] bg-[#161623] min-h-screen w-screen grid place-items-center pt-[2%]">
          <div className="flex flex-col">
            <div className=" relative">
              <img src="i1.png" className="object-cover" />
              <div className="bg-[#C358B3] top-[22%] h-[3px] w-[50%] absolute z-10"></div>
              <div className="bg-[#C358B3] top-[21.5%] h-[10px] w-[10px] rounded-full absolute z-10"></div>
              <div className="top-[18%] absolute z-10 -left-[22%] text-[32px] leading-tight">
                <p className="text-white font-bold">5km thing</p>
                <p className="text-[#9F9FFF]">
                  We show people
                  <br /> around you.
                </p>
              </div>
            </div>
            <div className="relative z-10">
              <img src="i2.png" className="object-cover -mt-[20%]" />
              <div className="bg-[#C358B3] -top-[20%] h-[3px] w-[50%] absolute z-10 right-0"></div>
              <div className="bg-[#C358B3] -top-[21%] h-[10px] w-[10px] rounded-full absolute z-10 right-0"></div>
              <div className="absolute z-10 text-[32px] leading-tight -top-[24%] -right-[33%]">
                <p className="text-white font-bold">People first</p>
                <p className="text-[#9F9FFF]">
                  We show people
                  <br /> around you.
                </p>
              </div>
            </div>
            <div className="relative z-10">
              <img src="i3.png" className="object-cover -mt-[15%]" />
              <div className="bg-[#C358B3] -top-[7%] h-[3px] w-[80%] absolute z-10"></div>
              <div className="bg-[#C358B3] -top-[7.5%] h-[10px] w-[10px] rounded-full absolute z-10"></div>
              <div className="-top-[9%] absolute z-10 -left-[23%] text-[32px] leading-tight">
                <p className="text-white font-bold">Filters</p>
                <p className="text-[#9F9FFF]">
                  Filters for unique
                  <br /> Groups
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full p-[5%] bg-black flex flex-row-reverse gap-[5%] items-center justify-center">
          <div className="flex flex-col gap-4">
            <div className="">
              <img src="i4.png" className="object-cover" />
            </div>
            <div className="">
              <img src="i5.png" className="object-cover" />
            </div>
            <div className="">
              <img src="i6.png" className="object-cover" />
            </div>
          </div>
          <div className="w-1/2">
            <h1 className="text-white font-bold text-[6vw] leading-[1]">
              Find your tribe.
            </h1>
            <p className="text-[#977FCC] text-[2.1vw] leading-tight">
              Finding people who are on the same wavelength as you are is now
              easier than ever.
            </p>
          </div>
        </section>
        <section className="w-full p-[5%] bg-black flex gap-[5%] flex-row-reverse items-center justify-center">
          <div className="">
            <img src="i7.png" className="object-cover" />
          </div>
          <div className="w-1/2">
            <h1 className="text-white font-bold text-[6vw] leading-[1]">
              Talk to people around you.
            </h1>
            <p className="text-[#977FCC] text-[1.8vw] leading-tight pt-[2%]">
              Share with people in your area. You never know who you might run
              into!
            </p>
          </div>
        </section>
        <section className="w-full p-[5%] bg-black flex flex-row-reverse gap-[5%] items-center justify-center">
          <div className="">
            <img src="i8.png" className="object-cover" />
          </div>
          <div className="w-1/2">
            <h1 className="text-white font-bold text-[6vw] leading-[1]">
              Communities unique to you.
            </h1>
            <p className="text-[#789FC3] text-[1.8vw] pt-[2%] leading-tight">
              Find and join citywide communities with individuals having similar
              interests, opinions, and backgrounds.
            </p>
          </div>
        </section>
        <section className="w-full p-[5%] bg-black grid place-items-center">
          <div className="">
            <h2 className="text-white text-[2.5vw] font-medium">
              In a world so connected, it can be really hard to make friends
            </h2>
            <h4 className="text-[2.1vw] text-[#A586A4] leading-tight">
              We are dedicated to building products which help you,
              <br /> inspire you and bring you joy
            </h4>
          </div>
        </section>
        <section className="w-full px-[15%] py-[5%] bg-[#161616] flex flex-row gap-[5%]">
          <div className="">
            <img src="i9.png" className="object-cover" />
          </div>
          <div className="flex flex-col">
            <h2 className="text-white font-bold text-[2vw]">
              Interested in what we are doing?
            </h2>
            <h4 className="text-[#B7B7B7] text-[1.5vw] leading-tight">
              We are team ninja working on this, you can get in touch with us on
              the emails below.
            </h4>
            <form action="#" className="flex flex-col w-fit gap-[25%] pt-[5%]">
              <input
                placeholder="Your name"
                type="text"
                required
                className="bg-transparent text-[#C9C9C9] border border-[#C9C9C9] p-[2%] focus:outline-none w-[150%]"
              />
              <input
                placeholder="Your email"
                type="email"
                required
                className="bg-transparent text-[#C9C9C9] border border-[#C9C9C9] p-[2%] focus:outline-none w-[150%]"
              />
            </form>
          </div>
        </section>
      </main>
    </>
  );
}
